version: "3.9"

services:
  # Base de données
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mdbrootpwdexample
      MARIADB_DATABASE: memory
      MARIADB_USER: memory
      MARIADB_PASSWORD: m0t2p@ssef0rt
    networks:
      - memorysite
  # Serveur PHP
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    image: php:8.0-apache
    ports:
      - "8000:80"
    restart: always
    volumes: ["./:/var/www/html"]
    environment:
      DB_HOST: db:3306
      DB_DATABASE: memory
      DB_USER: memory
      DB_PASSWORD: m0t2p@ssef0rt
      SERVER_URL: localhost:8000
    networks:
      - memorysite
networks:
  memorysite:
volumes:
  db_data:
